# Generated by Django 3.1 on 2022-05-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('biography', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('numberSold', models.IntegerField(default=0)),
                ('numAvailidInStock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='products/book/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255, null=True)),
                ('marterial', models.CharField(max_length=255, null=True)),
                ('countryOfOrigin', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('size', models.CharField(max_length=255, null=True)),
                ('importPrice', models.FloatField(default=0)),
                ('color', models.CharField(max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categoryclothes')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('techType', models.CharField(max_length=255, null=True)),
                ('typeCpu', models.CharField(max_length=255, null=True)),
                ('speed', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ram', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('battery', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('warranty', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('operationSystem', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cpu')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cpu', models.CharField(blank=True, max_length=200, null=True)),
                ('screen', models.CharField(blank=True, max_length=200, null=True)),
                ('ram', models.CharField(blank=True, max_length=200, null=True)),
                ('feature', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('operation_system', models.CharField(blank=True, max_length=200, null=True)),
                ('battery', models.CharField(blank=True, max_length=200, null=True)),
                ('warranty', models.CharField(blank=True, max_length=200, null=True)),
                ('backcamera', models.CharField(blank=True, max_length=200, null=True)),
                ('fontcamera', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('totalamount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('vram', models.CharField(max_length=255, null=True)),
                ('tech', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discountPercent', models.FloatField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('address_second', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, choices=[('0', 'Chờ xác nhận'), ('1', 'Đã xác nhận'), ('2', 'Đang giao hàng'), ('3', 'Giao hàng thành công'), ('4', 'Huỷ'), ('5', 'Giao hàng thất bại')], default='0', max_length=1)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.payment')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shipment')),
                ('voucher', models.ManyToManyField(blank=True, to='shop.Voucher')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePhoneItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('numberSold', models.IntegerField(default=0)),
                ('numAvailidInStock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='products/mobilephone/%Y/%m/%d')),
                ('mobilePhone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.mobilephone')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('numberSold', models.IntegerField(default=0)),
                ('numAvailidInStock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='products/laptop/%Y/%m/%d')),
                ('laptop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.laptop')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producer'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='vga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.vga'),
        ),
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('numberSold', models.IntegerField(default=0)),
                ('numAvailidInStock', models.IntegerField(default=0)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, upload_to='products/clothes/%Y/%m/%d')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='CartMobilePhoneItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('mobilephoneItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mobilephoneitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartLaptopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('laptopItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.laptopitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartClothesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('clothesItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.clothesitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartBookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bookItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.bookitem')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('publicationdate', models.CharField(blank=True, max_length=200, null=True)),
                ('numberofpage', models.DecimalField(decimal_places=0, max_digits=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.publisher')),
            ],
        ),
    ]
