# Generated by Django 3.1 on 2022-05-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipment', '0001_initial'),
        ('cart', '0001_initial'),
        ('payment', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('address_second', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(blank=True, choices=[('0', 'Chờ xác nhận'), ('1', 'Đã xác nhận'), ('2', 'Đang giao hàng'), ('3', 'Giao hàng thành công'), ('4', 'Huỷ'), ('5', 'Giao hàng thất bại')], default='0', max_length=1)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
            ],
        ),
    ]
