# Generated by Django 3.1 on 2022-05-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discountPercent', models.FloatField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ManyToManyField(blank=True, to='order.Voucher'),
        ),
    ]
